### ISSUE TITLE
Does not build with 4.5.1

### ISSUE THREAD

**Issue by attilaolah** [zo7/median-video#1]
Running `make` gives the following errors:

```
Scanning dependencies of target MedianVideo           
[ 50%] Building CXX object CMakeFiles/MedianVideo.dir/MedianVideo.cpp.o
/home/atl/third_party/github.com/somewacko/median-video/MedianVideo.cpp: In function ‘int main(int, char**)’:
/home/atl/third_party/github.com/somewacko/median-video/MedianVideo.cpp:59:49: error: ‘CV_CAP_PROP_FOURCC’ was not declared in this scope
   59 |     int ex = static_cast<int>(video_capture.get(CV_CAP_PROP_FOURCC));
      |                                                 ^~~~~~~~~~~~~~~~~~                                                                                     
/home/atl/third_party/github.com/somewacko/median-video/MedianVideo.cpp:60:50: error: ‘CV_CAP_PROP_FRAME_WIDTH’ was not declared in this scope
   60 |     cv::Size s = cv::Size((int)video_capture.get(CV_CAP_PROP_FRAME_WIDTH),                                            
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~
/home/atl/third_party/github.com/somewacko/median-video/MedianVideo.cpp:61:50: error: ‘CV_CAP_PROP_FRAME_HEIGHT’ was not declared in this scope
   61 |                           (int)video_capture.get(CV_CAP_PROP_FRAME_HEIGHT));
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/atl/third_party/github.com/somewacko/median-video/MedianVideo.cpp:62:33: error: ‘CV_CAP_PROP_FPS’ was not declared in this scope
   62 |     int fps = video_capture.get(CV_CAP_PROP_FPS);
      |                                 ^~~~~~~~~~~~~~~
/home/atl/third_party/github.com/somewacko/median-video/MedianVideo.cpp:73:41: error: ‘CV_CAP_PROP_FRAME_COUNT’ was not declared in this scope
   73 |     const int total = video_capture.get(CV_CAP_PROP_FRAME_COUNT);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/MedianVideo.dir/build.make:82: CMakeFiles/MedianVideo.dir/MedianVideo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/MedianVideo.dir/all] Error 2                                                                                 
make: *** [Makefile:103: all] Error 2                      
```
